function KBOCDResourceBars.layoutHealthOptionsPane()
    KBOCDResourceBars.CreateHealthBarOptionsDB()

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.checkBox.enable)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.checkBox.hideOutOfCombatAndFull)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.sectionHeader.sizeAndPosition)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.frameWidth)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.frameHeight)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.frameXPosition)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.frameYPosition)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.sectionHeader.barColors)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.colorSwatch.barColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.barColorAlpha)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.colorSwatch.depletionColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.depletionColorAlpha)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.sectionHeader.barGradient)
    local enableGradientColors, enableGradientColorsSetting = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.checkBox.enableGradientColors)
    local gradientColorSecondStopSwatch = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.colorSwatch.gradientColorSecondStop)
    gradientColorSecondStopSwatch:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)
    local gradientColorSecondStopSlider = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.barSecondStepAlpha)
    gradientColorSecondStopSlider:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)
    local gradientColorThirdStopSwatch = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.colorSwatch.gradientColorThirdStop)
    gradientColorThirdStopSwatch:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)
    local gradientColorThirdStopSlider = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.barThirdStepAlpha)
    gradientColorThirdStopSlider:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.sectionHeader.frameColors)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.colorSwatch.borderColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.borderColorAlpha)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.colorSwatch.backdropColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.backdropColorAlpha)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.sectionHeader.resourceText)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.dropDown.textValueDisplay)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.dropDown.textAlignment)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.textSize)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.colorSwatch.textColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.slider.textAlpha)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.HealthBarOptionsDB.checkBox.fontShadow)

end