function KBOCDResourceBars.layoutAdditionalResourceOptionsPane()
    KBOCDResourceBars.CreateAdditionalResourceBarOptionsDB()

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.checkBox.enable)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.checkBox.hideOutOfCombatAndFull)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.dropDown.additionalResource)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.sectionHeader.sizeAndPosition)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.frameWidth)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.frameHeight)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.frameXPosition)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.frameYPosition)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.sectionHeader.barColors)
    local resourceDeterminesBarColor, resourceDeterminesBarColorSetting = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.checkBox.resourceDeterminesBarColor)
    local barColor = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.colorSwatch.barColor)
    local barColorAlpha = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.barColorAlpha)
    barColor:SetParentInitializer(resourceDeterminesBarColor, function()
        return not resourceDeterminesBarColorSetting:GetValue()
    end)
        barColorAlpha:SetParentInitializer(resourceDeterminesBarColor, function()
        return not resourceDeterminesBarColorSetting:GetValue()
    end)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.colorSwatch.depletionColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.depletionColorAlpha)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.sectionHeader.barGradient)
    local enableGradientColors, enableGradientColorsSetting = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.checkBox.enableGradientColors)
    local gradientColorSecondStopSwatch = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.colorSwatch.gradientColorSecondStop)
    gradientColorSecondStopSwatch:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)
    local gradientColorSecondStopSlider = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.barSecondStepAlpha)
    gradientColorSecondStopSlider:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)
    local gradientColorThirdStopSwatch = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.colorSwatch.gradientColorThirdStop)
    gradientColorThirdStopSwatch:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)
    local gradientColorThirdStopSlider = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.barThirdStepAlpha)
    gradientColorThirdStopSlider:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.sectionHeader.frameColors)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.colorSwatch.borderColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.borderColorAlpha)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.colorSwatch.backdropColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.backdropColorAlpha)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.sectionHeader.resourceText)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.dropDown.textValueDisplay)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.dropDown.textAlignment)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.textSize)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.colorSwatch.textColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.slider.textAlpha)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.AdditionalResourceBarOptionsDB.checkBox.fontShadow)

end