function KBOCDResourceBars.layoutPrimaryResourceOptionsPane()
    KBOCDResourceBars.CreatePrimaryResourceBarOptionsDB()

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.checkBox.enable)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.checkBox.hideOutOfCombatAndFull)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.sectionHeader.sizeAndPosition)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.frameWidth)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.frameHeight)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.frameXPosition)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.frameYPosition)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.sectionHeader.barColors)
    local resourceDeterminesBarColor, resourceDeterminesBarColorSetting = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.checkBox.resourceDeterminesBarColor)
    local barColor = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.colorSwatch.barColor)
    local barColorAlpha = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.barColorAlpha)
    barColor:SetParentInitializer(resourceDeterminesBarColor, function()
        return not resourceDeterminesBarColorSetting:GetValue()
    end)
        barColorAlpha:SetParentInitializer(resourceDeterminesBarColor, function()
        return not resourceDeterminesBarColorSetting:GetValue()
    end)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.colorSwatch.depletionColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.depletionColorAlpha)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.sectionHeader.barGradient)
    local enableGradientColors, enableGradientColorsSetting = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.checkBox.enableGradientColors)
    local gradientColorSecondStopSwatch = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.colorSwatch.gradientColorSecondStop)
    gradientColorSecondStopSwatch:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)
    local gradientColorSecondStopSlider = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.barSecondStepAlpha)
    gradientColorSecondStopSlider:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)
    local gradientColorThirdStopSwatch = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.colorSwatch.gradientColorThirdStop)
    gradientColorThirdStopSwatch:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)
    local gradientColorThirdStopSlider = KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.barThirdStepAlpha)
    gradientColorThirdStopSlider:SetParentInitializer(enableGradientColors, function()
        return enableGradientColorsSetting:GetValue()
    end)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.sectionHeader.frameColors)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.colorSwatch.borderColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.borderColorAlpha)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.colorSwatch.backdropColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.backdropColorAlpha)

    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.sectionHeader.resourceText)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.dropDown.textValueDisplay)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.dropDown.textAlignment)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.textSize)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.colorSwatch.textColor)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.slider.textAlpha)
    KBOCD_UI.CreateUIElementFrom(KBOCDResourceBars.PrimaryResourceBarOptionsDB.checkBox.fontShadow)

end